sudo: required
language: generic
services:
- docker
before_install:
- docker build -t $REPO .
after_success:
- docker --version
- docker tag $REPO $REPO:latest
- docker tag $REPO $REPO:git-$COMMIT
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $REPO
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
